### ISSUE TITLE
Error on Ubuntu - Snappy not supported or corrupted Snappy compressed block contents'

### ISSUE THREAD

**Issue by mubaris** [twmht/python-rocksdb#43]
Installation of RocksDB and Python-RocksDB went smoothly.

Then I tried to access a db I got this error.

```
Traceback (most recent call last):
  File "main.py", line 57, in <module>
    name_v = vectorize(name_w)
  File "main.py", line 39, in vectorize
    x = db.get(k.encode())
  File "rocksdb/_rocksdb.pyx", line 1796, in rocksdb._rocksdb.DB.get
  File "rocksdb/_rocksdb.pyx", line 76, in rocksdb._rocksdb.check_status
rocksdb.errors.Corruption: b'Corruption: Snappy not supported or corrupted Snappy compressed block contents'
```

**Comment by twmht** [comment]
@mubaris 

Can you show the code which can reproduce the problem?

**Comment by mubaris** [comment]
I figured out to fix the issue. I tried to copy the DB generated in Mac and use it in Ubuntu system. Regenerating the DB on Ubuntu solved the issue
