### ISSUE TITLE
No attributes in rocksdb module

### ISSUE THREAD

**Issue by eeepmb** [twmht/python-rocksdb#59]
Hi guys,
I just tried to install the python-rocksdb lib and facing this problem. It seemed like everything worked just fine but when I try to run a basic script I get the following error:
```python3
python3 rocksdb.py 
Traceback (most recent call last):
  File "rocksdb.py", line 1, in <module>
    import rocksdb
  File "/Users/eeepmb/workspace/rocksdb.py", line 3, in <module>
    db = rocksdb.DB("test.db", rocksdb.Options(create_if_missing=True))
AttributeError: module 'rocksdb' has no attribute 'DB'
```

Unfortunately I don't have the original logging anymore but when I rerun the commands I get the following output.

```
brew install rocksdb
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 3 taps (homebrew/core, homebrew/cask and caskroom/cask).
==> New Formulae
anime-downloader
==> Updated Formulae
corectl vamp-plugin-sdk
Warning: rocksdb 6.1.2 is already installed and up-to-date
To reinstall 6.1.2, run brew reinstall rocksdb
```

```
pip3 install python-rocksdb
Requirement already satisfied: python-rocksdb in /usr/local/lib/python3.7/site-packages (0.7.0)
Requirement already satisfied: setuptools>=25 in /usr/local/lib/python3.7/site-packages (from python-rocksdb) (41.0.1)
```

I'm using Python 3.7.3 (.. but had the same issue with Python 3.6.5) on macOS Mojave v.10.14.5.
I already  googled a lot but couldn't find much on this. It's also weird because in my IDE (Visual Studio Code) the modules are listed when I type `rocksdb.`. 

Any help on this would be highly appreciated.

**Comment by eeepmb** [comment]
I just found the solution myself but for everyone else it is as simple as it gets:
The problem was that my `.py`script file was named rocksdb as well ...
