### ISSUE TITLE
pybind11 branch install failed

### ISSUE THREAD

**Issue by itboyljm** [twmht/python-rocksdb#80]
hello, I am using pyrocksdb of branch pybind11, while I was installing pyrocksdb according to the wiki of link:
https://github.com/twmht/python-rocksdb/tree/pybind11#quick-install
I met the failure whose error log is as follow:
[ 92%] Linking CXX executable db_bench
[ 94%] Built target pyrocksdb
Scanning dependencies of target range_del_aggregator_bench
[ 94%] Building CXX object lib/rocksdb/CMakeFiles/range_del_aggregator_bench.dir/db/range_del_aggregator_bench.cc.o
/usr/bin/ld: cannot find -ltestharness
collect2: error: ld returned 1 exit status
gmake[2]: *** [lib/rocksdb/table_reader_bench] Error 1
gmake[1]: *** [lib/rocksdb/CMakeFiles/table_reader_bench.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: CMakeFiles/db_bench.dir/tools/db_bench_tool.cc.o: undefined reference to symbol '_ZN6google15SetUsageMessageERKSs'
//usr/local/lib/libgflags.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[2]: *** [lib/rocksdb/db_bench] Error 1
gmake[1]: *** [lib/rocksdb/CMakeFiles/db_bench.dir/all] Error 2
/usr/bin/ld: CMakeFiles/hash_table_bench.dir/utilities/persistent_cache/hash_table_bench.cc.o: undefined reference to symbol '_ZN6google15SetUsageMessageERKSs'
//usr/local/lib/libgflags.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[2]: *** [lib/rocksdb/hash_table_bench] Error 1
gmake[1]: *** [lib/rocksdb/CMakeFiles/hash_table_bench.dir/all] Error 2
[ 94%] Linking CXX executable range_del_aggregator_bench
/usr/bin/ld: CMakeFiles/range_del_aggregator_bench.dir/db/range_del_aggregator_bench.cc.o: undefined reference to symbol '_ZN6google21ParseCommandLineFlagsEPiPPPcb'
//usr/local/lib/libgflags.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
gmake[2]: *** [lib/rocksdb/range_del_aggregator_bench] Error 1
gmake[1]: *** [lib/rocksdb/CMakeFiles/range_del_aggregator_bench.dir/all] Error 2
gmake: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 125, in <module>
    zip_safe=False,
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/data/projects/fate/common/miniconda3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/data/projects/fate/common/miniconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/data/projects/fate/common/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/data/projects/fate/common/miniconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/data/projects/fate/common/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/data/projects/fate/common/miniconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/data/projects/fate/common/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/data/projects/fate/common/python/venv/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/data/projects/fate/common/miniconda3/lib/python3.6/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/data/projects/fate/common/miniconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/data/projects/fate/common/miniconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    self.build_extension(ext)
  File "setup.py", line 76, in build_extension
    cwd=self.build_temp)
  File "/data/projects/fate/common/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.

**Comment by itboyljm** [comment]
I am confused about that, because I successfully installed pyrocksdb of master branch and am using it right now. So, I think the dependencies are fully installed :)

**Comment by xyb** [comment]
This looks like a rocksdb [issue](https://github.com/facebook/rocksdb/pull/7040), you may need to update to the latest source code to compile it:
```
cd lib/rocksdb
git checkout master
git pull
cd ../..
python setup.py install
```
